env:
  node: true
  es6: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 2017
  sourceType: module

extends:
  - 'airbnb-base'

plugins:
  - import

rules:
  no-useless-escape: 0
  no-console: 0